-- Generated by tooling/bootstrap/generate-schema.mjs. MySQL 8.4.
-- Public DO fields are authoritative; H2 tests supply type hints only.
SET NAMES utf8mb4;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessDO.java
CREATE TABLE IF NOT EXISTS `crm_business` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `customer_id` bigint NULL,
  `follow_up_status` bit(1) NULL,
  `contact_last_time` datetime NULL,
  `contact_next_time` datetime NULL,
  `owner_user_id` bigint NULL,
  `status_type_id` bigint NULL,
  `status_id` bigint NULL,
  `end_status` int NULL,
  `end_remark` text NULL,
  `deal_time` datetime NULL,
  `total_product_price` decimal(24,6) NULL,
  `discount_percent` decimal(24,6) NULL,
  `total_price` decimal(24,6) NULL,
  `remark` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessProductDO.java
CREATE TABLE IF NOT EXISTS `crm_business_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `business_id` bigint NULL,
  `product_id` bigint NULL,
  `product_price` decimal(24,6) NULL,
  `business_price` decimal(24,6) NULL,
  `count` decimal(24,6) NULL,
  `total_price` decimal(24,6) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessStatusDO.java
CREATE TABLE IF NOT EXISTS `crm_business_status` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `type_id` bigint NULL,
  `name` varchar(255) NULL,
  `percent` int NULL,
  `sort` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/business/CrmBusinessStatusTypeDO.java
CREATE TABLE IF NOT EXISTS `crm_business_status_type` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `dept_ids` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/clue/CrmClueDO.java
CREATE TABLE IF NOT EXISTS `crm_clue` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `education_member_id` bigint NULL,
  `education_student_id` bigint NULL,
  `education_course_id` bigint NULL,
  `education_consent_time` datetime NULL,
  `education_consent_version` varchar(64) NULL,
  `education_service_type` varchar(32) NULL,
  `education_teacher_id` bigint NULL,
  `education_teacher_name` varchar(80) NULL,
  `education_preferred_start_time` datetime NULL,
  `education_preferred_end_time` datetime NULL,
  `education_appointment_status` varchar(32) NULL,
  `name` varchar(255) NULL,
  `follow_up_status` bit NOT NULL DEFAULT b'0',
  `contact_last_time` datetime NULL,
  `contact_last_content` text NULL,
  `contact_next_time` datetime NULL,
  `owner_user_id` bigint NULL,
  `transform_status` bit NOT NULL DEFAULT b'0',
  `customer_id` bigint NULL,
  `mobile` varchar(255) NULL,
  `telephone` varchar(255) NULL,
  `qq` varchar(255) NULL,
  `wechat` varchar(255) NULL,
  `email` varchar(255) NULL,
  `area_id` int NULL,
  `detail_address` text NULL,
  `industry_id` int NULL,
  `level` int NULL,
  `source` int NULL,
  `remark` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_education_member` (`tenant_id`, `education_member_id`, `education_student_id`),
  KEY `idx_education_appointment` (`tenant_id`, `education_member_id`, `education_student_id`, `education_service_type`, `education_appointment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contact/CrmContactDO.java
CREATE TABLE IF NOT EXISTS `crm_contact` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `customer_id` bigint NULL,
  `contact_last_time` datetime NULL,
  `contact_last_content` text NULL,
  `contact_next_time` datetime NULL,
  `owner_user_id` bigint NULL,
  `mobile` varchar(255) NULL,
  `telephone` varchar(255) NULL,
  `email` varchar(255) NULL,
  `qq` bigint NULL,
  `wechat` varchar(255) NULL,
  `area_id` int NULL,
  `detail_address` text NULL,
  `sex` int NULL,
  `master` bit(1) NULL,
  `post` varchar(255) NULL,
  `parent_id` bigint NULL,
  `remark` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contact/CrmContactBusinessDO.java
CREATE TABLE IF NOT EXISTS `crm_contact_business` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `contact_id` bigint NULL,
  `business_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contract/CrmContractDO.java
CREATE TABLE IF NOT EXISTS `crm_contract` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `no` varchar(255) NULL,
  `customer_id` bigint NULL,
  `business_id` bigint NULL,
  `contact_last_time` datetime NULL,
  `owner_user_id` bigint NULL,
  `process_instance_id` varchar(255) NULL,
  `audit_status` int NULL,
  `order_date` datetime NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `total_product_price` decimal(24,6) NULL,
  `discount_percent` decimal(24,6) NULL,
  `total_price` decimal(24,6) NULL,
  `sign_contact_id` bigint NULL,
  `sign_user_id` bigint NULL,
  `remark` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contract/CrmContractConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_contract_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `notify_enabled` bit(1) NULL,
  `notify_days` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/contract/CrmContractProductDO.java
CREATE TABLE IF NOT EXISTS `crm_contract_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `contract_id` bigint NULL,
  `product_id` bigint NULL,
  `product_price` decimal(24,6) NULL,
  `contract_price` decimal(24,6) NULL,
  `count` decimal(24,6) NULL,
  `total_price` decimal(24,6) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/customer/CrmCustomerDO.java
CREATE TABLE IF NOT EXISTS `crm_customer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `follow_up_status` bit(1) NULL,
  `contact_last_time` datetime NULL,
  `contact_last_content` text NULL,
  `contact_next_time` datetime NULL,
  `owner_user_id` bigint NULL,
  `owner_time` datetime NULL,
  `lock_status` bit(1) NULL,
  `deal_status` bit(1) NULL,
  `mobile` varchar(255) NULL,
  `telephone` varchar(255) NULL,
  `qq` varchar(255) NULL,
  `wechat` varchar(255) NULL,
  `email` varchar(255) NULL,
  `area_id` int NULL,
  `detail_address` text NULL,
  `industry_id` int NULL,
  `level` int NULL,
  `source` int NULL,
  `remark` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/customer/CrmCustomerLimitConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_customer_limit_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `type` int NULL,
  `user_ids` text NULL,
  `dept_ids` text NULL,
  `max_count` int NULL,
  `deal_count_enabled` bit(1) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/customer/CrmCustomerPoolConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_customer_pool_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `enabled` bit(1) NULL,
  `contact_expire_days` int NULL,
  `deal_expire_days` int NULL,
  `notify_enabled` bit(1) NULL,
  `notify_days` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/followup/CrmFollowUpRecordDO.java
CREATE TABLE IF NOT EXISTS `crm_follow_up_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `biz_type` int NULL,
  `biz_id` bigint NULL,
  `type` int NULL,
  `content` text NULL,
  `next_time` datetime NULL,
  `pic_urls` text NULL,
  `file_urls` text NULL,
  `business_ids` text NULL,
  `contact_ids` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/permission/CrmOwnerRecordDO.java
CREATE TABLE IF NOT EXISTS `crm_owner_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `biz_type` int NULL,
  `biz_id` bigint NULL,
  `pre_owner_user_id` bigint NULL,
  `post_owner_user_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/performance/CrmPerformanceConfigDO.java
CREATE TABLE IF NOT EXISTS `crm_performance_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `biz_type` int NULL,
  `object_id` bigint NULL,
  `object_type` int NULL,
  `year` int NULL,
  `year_target_price` decimal(24,6) NULL,
  `january_target_price` decimal(24,6) NULL,
  `february_target_price` decimal(24,6) NULL,
  `march_target_price` decimal(24,6) NULL,
  `april_target_price` decimal(24,6) NULL,
  `may_target_price` decimal(24,6) NULL,
  `june_target_price` decimal(24,6) NULL,
  `july_target_price` decimal(24,6) NULL,
  `august_target_price` decimal(24,6) NULL,
  `september_target_price` decimal(24,6) NULL,
  `october_target_price` decimal(24,6) NULL,
  `november_target_price` decimal(24,6) NULL,
  `december_target_price` decimal(24,6) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/permission/CrmPermissionDO.java
CREATE TABLE IF NOT EXISTS `crm_permission` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `biz_type` int NULL,
  `biz_id` bigint NULL,
  `user_id` bigint NULL,
  `level` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/product/CrmProductDO.java
CREATE TABLE IF NOT EXISTS `crm_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `no` varchar(255) NULL,
  `unit` int NULL,
  `price` decimal(24,6) NULL,
  `status` int NULL,
  `category_id` bigint NULL,
  `description` text NULL,
  `owner_user_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/product/CrmProductCategoryDO.java
CREATE TABLE IF NOT EXISTS `crm_product_category` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `parent_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/receivable/CrmReceivableDO.java
CREATE TABLE IF NOT EXISTS `crm_receivable` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(255) NULL,
  `plan_id` bigint NULL,
  `customer_id` bigint NULL,
  `contract_id` bigint NULL,
  `owner_user_id` bigint NULL,
  `return_time` datetime NULL,
  `return_type` int NULL,
  `price` decimal(24,6) NULL,
  `remark` text NULL,
  `process_instance_id` varchar(255) NULL,
  `audit_status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-crm/src/main/java/cn/iocoder/yudao/module/crm/dal/dataobject/receivable/CrmReceivablePlanDO.java
CREATE TABLE IF NOT EXISTS `crm_receivable_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `period` int NULL,
  `customer_id` bigint NULL,
  `contract_id` bigint NULL,
  `owner_user_id` bigint NULL,
  `return_time` datetime NULL,
  `return_type` int NULL,
  `price` decimal(24,6) NULL,
  `receivable_id` bigint NULL,
  `remind_days` int NULL,
  `remind_time` datetime NULL,
  `remark` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/address/MemberAddressDO.java
CREATE TABLE IF NOT EXISTS `member_address` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NULL,
  `name` varchar(10) NULL,
  `mobile` varchar(20) NULL,
  `area_id` bigint(20) NULL,
  `detail_address` varchar(250) NULL,
  `default_status` bit NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/config/MemberConfigDO.java
CREATE TABLE IF NOT EXISTS `member_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `point_trade_deduct_enable` bit(1) NULL,
  `point_trade_deduct_unit_price` int NULL,
  `point_trade_deduct_max_price` int NULL,
  `point_trade_give_point` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/level/MemberExperienceRecordDO.java
CREATE TABLE IF NOT EXISTS `member_experience_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `biz_type` int NULL,
  `biz_id` varchar(255) NULL,
  `title` varchar(255) NULL,
  `description` text NULL,
  `experience` int NULL,
  `total_experience` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/group/MemberGroupDO.java
CREATE TABLE IF NOT EXISTS `member_group` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `remark` varchar(255) NULL,
  `status` tinyint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/level/MemberLevelDO.java
CREATE TABLE IF NOT EXISTS `member_level` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `level` int NULL,
  `experience` int NULL,
  `discount_percent` int NULL,
  `icon` varchar(255) NULL,
  `background_url` varchar(255) NULL,
  `status` tinyint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/level/MemberLevelRecordDO.java
CREATE TABLE IF NOT EXISTS `member_level_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `level_id` bigint NULL,
  `level` int NULL,
  `discount_percent` int NULL,
  `experience` int NULL,
  `user_experience` int NULL,
  `remark` text NULL,
  `description` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/point/MemberPointRecordDO.java
CREATE TABLE IF NOT EXISTS `member_point_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `biz_id` varchar(255) NULL,
  `biz_type` int NULL,
  `title` varchar(255) NULL,
  `description` text NULL,
  `point` int NULL,
  `total_point` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/signin/MemberSignInConfigDO.java
CREATE TABLE IF NOT EXISTS `member_sign_in_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `day` int NULL,
  `point` int NULL,
  `experience` int NULL,
  `status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/signin/MemberSignInRecordDO.java
CREATE TABLE IF NOT EXISTS `member_sign_in_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `day` int NULL,
  `point` int NULL,
  `experience` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/tag/MemberTagDO.java
CREATE TABLE IF NOT EXISTS `member_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-member/src/main/java/cn/iocoder/yudao/module/member/dal/dataobject/user/MemberUserDO.java
CREATE TABLE IF NOT EXISTS `member_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `mobile` varchar(11) NULL,
  `email` varchar(50) NULL,
  `password` varchar(100) NULL,
  `status` tinyint NULL,
  `register_ip` varchar(32) NULL,
  `register_terminal` int NULL,
  `login_ip` varchar(50) NULL,
  `login_date` datetime NULL,
  `nickname` varchar(30) NULL,
  `avatar` varchar(255) NULL,
  `name` varchar(30) NULL,
  `sex` tinyint NULL,
  `birthday` datetime NULL,
  `area_id` int NULL,
  `mark` varchar(255) NULL,
  `point` int NULL,
  `tag_ids` text NULL,
  `level_id` bigint NULL,
  `experience` bigint NULL,
  `group_id` bigint NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`),
  UNIQUE KEY `uk_mobile_tenant_deleted` (`mobile`, `tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/app/PayAppDO.java
CREATE TABLE IF NOT EXISTS `pay_app` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `app_key` varchar(64) NULL,
  `name` varchar(64) NULL,
  `status` tinyint NULL,
  `remark` varchar(255) NULL,
  `order_notify_url` varchar(1024) NULL,
  `refund_notify_url` varchar(1024) NULL,
  `transfer_notify_url` text NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`),
  UNIQUE KEY `uk_app_key_deleted` (`app_key`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/channel/PayChannelDO.java
CREATE TABLE IF NOT EXISTS `pay_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(32) NULL,
  `status` tinyint(4) NULL,
  `fee_rate` double NULL,
  `remark` varchar(255) NULL,
  `app_id` bigint(20) NULL,
  `config` text NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/demo/PayDemoOrderDO.java
CREATE TABLE IF NOT EXISTS `pay_demo_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `spu_id` bigint NULL,
  `spu_name` varchar(255) NULL,
  `price` int NULL,
  `pay_status` bit(1) NULL,
  `pay_order_id` bigint NULL,
  `pay_time` datetime NULL,
  `pay_channel_code` varchar(255) NULL,
  `pay_refund_id` bigint NULL,
  `refund_price` int NULL,
  `refund_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/demo/PayDemoWithdrawDO.java
CREATE TABLE IF NOT EXISTS `pay_demo_withdraw` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `subject` varchar(255) NULL,
  `price` int NULL,
  `user_account` varchar(255) NULL,
  `user_name` varchar(255) NULL,
  `type` int NULL,
  `status` int NULL,
  `pay_transfer_id` bigint NULL,
  `transfer_channel_code` varchar(255) NULL,
  `transfer_time` datetime NULL,
  `transfer_error_msg` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/notify/PayNotifyLogDO.java
CREATE TABLE IF NOT EXISTS `pay_notify_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint(20) NULL,
  `notify_times` int NULL,
  `response` varchar(1024) NULL,
  `status` tinyint(4) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/notify/PayNotifyTaskDO.java
CREATE TABLE IF NOT EXISTS `pay_notify_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `app_id` bigint(20) NULL,
  `type` tinyint(4) NULL,
  `data_id` bigint(20) NULL,
  `merchant_order_id` varchar(64) NULL,
  `merchant_refund_id` varchar(255) NULL,
  `merchant_transfer_id` varchar(255) NULL,
  `status` tinyint(4) NULL,
  `next_notify_time` datetime(0) NULL,
  `last_execute_time` datetime(0) NULL,
  `notify_times` int NULL,
  `max_notify_times` int NULL,
  `notify_url` varchar(1024) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/order/PayOrderDO.java
CREATE TABLE IF NOT EXISTS `pay_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `app_id` bigint(20) NULL,
  `channel_id` bigint(20) NULL,
  `channel_code` varchar(32) NULL,
  `user_id` bigint(20) NULL,
  `user_type` tinyint(4) NULL,
  `merchant_order_id` varchar(64) NULL,
  `subject` varchar(32) NULL,
  `body` varchar(128) NULL,
  `notify_url` varchar(1024) NULL,
  `price` bigint(20) NULL,
  `channel_fee_rate` double NULL,
  `channel_fee_price` bigint(20) NULL,
  `status` tinyint(4) NULL,
  `user_ip` varchar(50) NULL,
  `expire_time` datetime NULL,
  `success_time` datetime(0) NULL,
  `extension_id` bigint(20) NULL,
  `no` varchar(64) NULL,
  `refund_price` bigint(20) NULL,
  `channel_user_id` varchar(255) NULL,
  `channel_order_no` varchar(64) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/order/PayOrderExtensionDO.java
CREATE TABLE IF NOT EXISTS `pay_order_extension` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) NULL,
  `order_id` bigint(20) NULL,
  `channel_id` bigint(20) NULL,
  `channel_code` varchar(32) NULL,
  `user_ip` varchar(50) NULL,
  `status` tinyint(4) NULL,
  `channel_extras` text NULL,
  `channel_error_code` varchar(64) NULL,
  `channel_error_msg` varchar(64) NULL,
  `channel_notify_data` varchar(1024) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/refund/PayRefundDO.java
CREATE TABLE IF NOT EXISTS `pay_refund` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) NULL,
  `app_id` bigint(20) NULL,
  `channel_id` bigint(20) NULL,
  `channel_code` varchar(32) NULL,
  `order_id` bigint(20) NULL,
  `order_no` varchar(64) NULL,
  `user_id` bigint(20) NULL,
  `user_type` tinyint(4) NULL,
  `merchant_order_id` varchar(64) NULL,
  `merchant_refund_id` varchar(64) NULL,
  `notify_url` varchar(1024) NULL,
  `status` tinyint(4) NULL,
  `pay_price` bigint(20) NULL,
  `refund_price` bigint(20) NULL,
  `reason` varchar(256) NULL,
  `user_ip` varchar(50) NULL,
  `channel_order_no` varchar(64) NULL,
  `channel_refund_no` varchar(64) NULL,
  `success_time` datetime(0) NULL,
  `channel_error_code` varchar(128) NULL,
  `channel_error_msg` varchar(256) NULL,
  `channel_notify_data` varchar(1024) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/transfer/PayTransferDO.java
CREATE TABLE IF NOT EXISTS `pay_transfer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) NULL,
  `app_id` bigint(20) NULL,
  `channel_id` bigint(20) NULL,
  `channel_code` varchar(32) NULL,
  `user_id` bigint(20) NULL,
  `user_type` tinyint(4) NULL,
  `merchant_transfer_id` varchar(64) NULL,
  `subject` varchar(256) NULL,
  `price` bigint(20) NULL,
  `user_account` varchar(256) NULL,
  `user_name` varchar(64) NULL,
  `status` tinyint(4) NULL,
  `success_time` datetime(0) NULL,
  `notify_url` varchar(1024) NULL,
  `user_ip` varchar(50) NULL,
  `channel_extras` text NULL,
  `channel_transfer_no` varchar(64) NULL,
  `channel_error_code` varchar(128) NULL,
  `channel_error_msg` varchar(256) NULL,
  `channel_notify_data` varchar(1024) NULL,
  `channel_package_info` varchar(1024) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `user_type` int NULL,
  `balance` int NULL,
  `freeze_price` int NULL,
  `total_expense` int NULL,
  `total_recharge` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletRechargeDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet_recharge` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `wallet_id` bigint NULL,
  `total_price` int NULL,
  `pay_price` int NULL,
  `bonus_price` int NULL,
  `package_id` bigint NULL,
  `pay_status` bit(1) NULL,
  `pay_order_id` bigint NULL,
  `pay_channel_code` varchar(255) NULL,
  `pay_time` datetime NULL,
  `pay_refund_id` bigint NULL,
  `refund_total_price` int NULL,
  `refund_pay_price` int NULL,
  `refund_bonus_price` int NULL,
  `refund_time` datetime NULL,
  `refund_status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletRechargePackageDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet_recharge_package` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `pay_price` int NULL,
  `bonus_price` int NULL,
  `status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-pay/src/main/java/cn/iocoder/yudao/module/pay/dal/dataobject/wallet/PayWalletTransactionDO.java
CREATE TABLE IF NOT EXISTS `pay_wallet_transaction` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(255) NULL,
  `wallet_id` bigint NULL,
  `biz_type` int NULL,
  `biz_id` varchar(255) NULL,
  `title` varchar(255) NULL,
  `price` int NULL,
  `balance` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/brand/ProductBrandDO.java
CREATE TABLE IF NOT EXISTS `product_brand` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `pic_url` varchar(255) NULL,
  `sort` int NULL,
  `description` varchar(1024) NULL,
  `status` tinyint NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/history/ProductBrowseHistoryDO.java
CREATE TABLE IF NOT EXISTS `product_browse_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `spu_id` bigint NULL,
  `user_id` bigint NULL,
  `user_deleted` bit(1) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/category/ProductCategoryDO.java
CREATE TABLE IF NOT EXISTS `product_category` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `parent_id` bigint NULL,
  `name` varchar(255) NULL,
  `pic_url` varchar(255) NULL,
  `sort` int NULL,
  `status` tinyint NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/comment/ProductCommentDO.java
CREATE TABLE IF NOT EXISTS `product_comment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `user_nickname` varchar(255) NULL,
  `user_avatar` varchar(255) NULL,
  `anonymous` bit(1) NULL,
  `order_id` bigint NULL,
  `order_item_id` bigint NULL,
  `spu_id` bigint NULL,
  `spu_name` varchar(255) NULL,
  `sku_id` bigint NULL,
  `sku_pic_url` text NULL,
  `sku_properties` text NULL,
  `visible` bit(1) NULL,
  `scores` int NULL,
  `description_scores` int NULL,
  `benefit_scores` int NULL,
  `content` text NULL,
  `pic_urls` text NULL,
  `reply_status` bit(1) NULL,
  `reply_user_id` bigint NULL,
  `reply_content` text NULL,
  `reply_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/favorite/ProductFavoriteDO.java
CREATE TABLE IF NOT EXISTS `product_favorite` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `spu_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/property/ProductPropertyDO.java
CREATE TABLE IF NOT EXISTS `product_property` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NULL,
  `remark` varchar(255) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/property/ProductPropertyValueDO.java
CREATE TABLE IF NOT EXISTS `product_property_value` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `property_id` bigint NULL,
  `name` varchar(128) NULL,
  `remark` varchar(255) NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/sku/ProductSkuDO.java
CREATE TABLE IF NOT EXISTS `product_sku` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `spu_id` bigint NULL,
  `properties` text NULL,
  `price` int NULL,
  `market_price` int NULL,
  `cost_price` int NULL,
  `bar_code` varchar(64) NULL,
  `pic_url` varchar(256) NULL,
  `stock` int NULL,
  `weight` double NULL,
  `volume` double NULL,
  `first_brokerage_price` int NULL,
  `second_brokerage_price` int NULL,
  `sales_count` int NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-product/src/main/java/cn/iocoder/yudao/module/product/dal/dataobject/spu/ProductSpuDO.java
CREATE TABLE IF NOT EXISTS `product_spu` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NULL,
  `keyword` varchar(256) NULL,
  `introduction` varchar(256) NULL,
  `description` text NULL,
  `category_id` bigint NULL,
  `brand_id` int NULL,
  `pic_url` varchar(256) NULL,
  `slider_pic_urls` text NULL,
  `sort` int NULL,
  `status` tinyint NULL,
  `spec_type` bit(1) NULL,
  `price` int NULL,
  `market_price` int NULL,
  `cost_price` int NULL,
  `stock` int NULL,
  `delivery_types` text NULL,
  `delivery_template_id` bigint NULL,
  `give_integral` int NULL,
  `sub_commission_type` bit(1) NULL,
  `sales_count` int NULL,
  `virtual_sales_count` int NULL,
  `browse_count` int NULL,
  `creator` varchar(64) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-statistics/src/main/java/cn/iocoder/yudao/module/statistics/dal/dataobject/product/ProductStatisticsDO.java
CREATE TABLE IF NOT EXISTS `product_statistics` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `time` date NULL,
  `spu_id` bigint NULL,
  `browse_count` int NULL,
  `browse_user_count` int NULL,
  `favorite_count` int NULL,
  `cart_count` int NULL,
  `order_count` int NULL,
  `order_pay_count` int NULL,
  `order_pay_price` int NULL,
  `after_sale_count` int NULL,
  `after_sale_refund_price` int NULL,
  `browse_convert_percent` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/article/ArticleDO.java
CREATE TABLE IF NOT EXISTS `promotion_article` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `category_id` bigint NULL,
  `spu_id` bigint NULL,
  `title` varchar(255) NULL,
  `author` varchar(255) NULL,
  `pic_url` varchar(255) NULL,
  `introduction` varchar(255) NULL,
  `browse_count` int NULL,
  `sort` int NULL,
  `status` int NULL,
  `recommend_hot` bit NULL,
  `recommend_banner` bit NULL,
  `content` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/article/ArticleCategoryDO.java
CREATE TABLE IF NOT EXISTS `promotion_article_category` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `pic_url` varchar(255) NULL,
  `status` int NULL,
  `sort` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/banner/BannerDO.java
CREATE TABLE IF NOT EXISTS `promotion_banner` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NULL,
  `url` text NULL,
  `pic_url` text NULL,
  `sort` int NULL,
  `status` int NULL,
  `position` int NULL,
  `memo` varchar(255) NULL,
  `browse_count` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/bargain/BargainActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_bargain_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `status` int NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `bargain_first_price` int NULL,
  `bargain_min_price` int NULL,
  `stock` int NULL,
  `total_stock` int NULL,
  `help_max_count` int NULL,
  `bargain_count` int NULL,
  `total_limit_count` int NULL,
  `random_min_price` int NULL,
  `random_max_price` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/bargain/BargainHelpDO.java
CREATE TABLE IF NOT EXISTS `promotion_bargain_help` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `activity_id` bigint NULL,
  `record_id` bigint NULL,
  `user_id` bigint NULL,
  `reduce_price` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/bargain/BargainRecordDO.java
CREATE TABLE IF NOT EXISTS `promotion_bargain_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `activity_id` bigint NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `bargain_first_price` int NULL,
  `bargain_price` int NULL,
  `status` int NULL,
  `end_time` datetime NULL,
  `order_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/combination/CombinationActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_combination_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `spu_id` bigint NULL,
  `total_limit_count` int NULL,
  `single_limit_count` int NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `user_size` int NULL,
  `virtual_group` bit(1) NULL,
  `status` int NULL,
  `limit_duration` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/combination/CombinationProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_combination_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `activity_id` bigint NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `combination_price` int NULL,
  `activity_status` int NULL,
  `activity_start_time` datetime NULL,
  `activity_end_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/combination/CombinationRecordDO.java
CREATE TABLE IF NOT EXISTS `promotion_combination_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `activity_id` bigint NULL,
  `combination_price` int NULL,
  `spu_id` bigint NULL,
  `spu_name` varchar(255) NULL,
  `pic_url` varchar(255) NULL,
  `sku_id` bigint NULL,
  `count` int NULL,
  `user_id` bigint NULL,
  `nickname` varchar(255) NULL,
  `avatar` varchar(255) NULL,
  `head_id` bigint NULL,
  `status` int NULL,
  `order_id` bigint NULL,
  `user_size` int NULL,
  `user_count` int NULL,
  `virtual_group` bit NULL,
  `expire_time` datetime NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/coupon/CouponDO.java
CREATE TABLE IF NOT EXISTS `promotion_coupon` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NULL,
  `name` varchar(255) NULL,
  `status` int NULL,
  `user_id` bigint NULL,
  `take_type` int NULL,
  `use_price` int NULL,
  `valid_start_time` datetime NULL,
  `valid_end_time` datetime NULL,
  `product_scope` int NULL,
  `product_scope_values` text NULL,
  `discount_type` int NULL,
  `discount_percent` int NULL,
  `discount_price` int NULL,
  `discount_limit_price` int NULL,
  `use_order_id` bigint NULL,
  `use_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/coupon/CouponTemplateDO.java
CREATE TABLE IF NOT EXISTS `promotion_coupon_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `description` varchar(255) NULL,
  `status` int NULL,
  `total_count` int NULL,
  `take_limit_count` int NULL,
  `take_type` int NULL,
  `use_price` int NULL,
  `product_scope` int NULL,
  `product_scope_values` text NULL,
  `validity_type` int NULL,
  `valid_start_time` datetime NULL,
  `valid_end_time` datetime NULL,
  `fixed_start_term` int NULL,
  `fixed_end_term` int NULL,
  `discount_type` int NULL,
  `discount_percent` int NULL,
  `discount_price` int NULL,
  `discount_limit_price` int NULL,
  `take_count` int NOT NULL DEFAULT 0,
  `use_count` int NOT NULL DEFAULT 0,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/discount/DiscountActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_discount_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `status` int NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `remark` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/discount/DiscountProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_discount_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `activity_id` bigint NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `discount_type` int NULL,
  `discount_percent` int NULL,
  `discount_price` int NULL,
  `activity_name` varchar(255) NULL,
  `activity_status` int NULL,
  `activity_start_time` datetime NULL,
  `activity_end_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/diy/DiyPageDO.java
CREATE TABLE IF NOT EXISTS `promotion_diy_page` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NULL,
  `name` varchar(255) NULL,
  `remark` varchar(255) NULL,
  `preview_pic_urls` text NULL,
  `property` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/diy/DiyTemplateDO.java
CREATE TABLE IF NOT EXISTS `promotion_diy_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `used` bit NULL,
  `used_time` datetime NULL,
  `remark` varchar(255) NULL,
  `preview_pic_urls` text NULL,
  `property` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/kefu/KeFuConversationDO.java
CREATE TABLE IF NOT EXISTS `promotion_kefu_conversation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `last_message_time` datetime NULL,
  `last_message_content` text NULL,
  `last_message_content_type` int NULL,
  `admin_pinned` bit(1) NULL,
  `user_deleted` bit(1) NULL,
  `admin_deleted` bit(1) NULL,
  `admin_unread_message_count` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/kefu/KeFuMessageDO.java
CREATE TABLE IF NOT EXISTS `promotion_kefu_message` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `conversation_id` bigint NULL,
  `sender_id` bigint NULL,
  `sender_type` int NULL,
  `receiver_id` bigint NULL,
  `receiver_type` int NULL,
  `content_type` int NULL,
  `content` text NULL,
  `read_status` bit(1) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/point/PointActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_point_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `spu_id` bigint NULL,
  `status` int NULL,
  `remark` text NULL,
  `sort` int NULL,
  `stock` int NULL,
  `total_stock` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/point/PointProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_point_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `activity_id` bigint NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `count` int NULL,
  `point` int NULL,
  `price` int NULL,
  `stock` int NULL,
  `activity_status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/reward/RewardActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_reward_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `status` int NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `remark` varchar(255) NULL,
  `condition_type` int NULL,
  `product_scope` int NULL,
  `product_scope_values` text NULL,
  `rules` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/seckill/SeckillActivityDO.java
CREATE TABLE IF NOT EXISTS `promotion_seckill_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `spu_id` bigint NULL,
  `name` varchar(255) NULL,
  `status` int NULL,
  `remark` varchar(255) NULL,
  `start_time` datetime NULL,
  `end_time` datetime NULL,
  `sort` int NULL,
  `config_ids` text NULL,
  `total_limit_count` int NULL,
  `single_limit_count` int NULL,
  `stock` int NULL,
  `total_stock` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/seckill/SeckillConfigDO.java
CREATE TABLE IF NOT EXISTS `promotion_seckill_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `start_time` varchar(255) NULL,
  `end_time` varchar(255) NULL,
  `slider_pic_urls` text NULL,
  `status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-promotion/src/main/java/cn/iocoder/yudao/module/promotion/dal/dataobject/seckill/SeckillProductDO.java
CREATE TABLE IF NOT EXISTS `promotion_seckill_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `activity_id` bigint NULL,
  `config_ids` text NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `seckill_price` int NULL,
  `stock` int NULL,
  `activity_status` int NULL,
  `activity_start_time` datetime NULL,
  `activity_end_time` datetime NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/aftersale/AfterSaleDO.java
CREATE TABLE IF NOT EXISTS `trade_after_sale` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(255) NULL,
  `status` int NULL,
  `way` int NULL,
  `type` int NULL,
  `user_id` bigint NULL,
  `apply_reason` varchar(255) NULL,
  `apply_description` varchar(255) NULL,
  `apply_pic_urls` text NULL,
  `order_id` bigint NULL,
  `order_no` varchar(255) NULL,
  `order_item_id` bigint NULL,
  `spu_id` bigint NULL,
  `spu_name` varchar(255) NULL,
  `sku_id` bigint NULL,
  `properties` text NULL,
  `pic_url` varchar(255) NULL,
  `count` int NULL,
  `audit_time` datetime NULL,
  `audit_user_id` bigint NULL,
  `audit_reason` varchar(255) NULL,
  `refund_price` int NULL,
  `pay_refund_id` bigint NULL,
  `refund_time` datetime NULL,
  `logistics_id` bigint NULL,
  `logistics_no` varchar(255) NULL,
  `delivery_time` datetime NULL,
  `receive_time` datetime NULL,
  `receive_reason` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/aftersale/AfterSaleLogDO.java
CREATE TABLE IF NOT EXISTS `trade_after_sale_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `user_type` int NULL,
  `after_sale_id` bigint NULL,
  `before_status` int NULL,
  `after_status` int NULL,
  `operate_type` int NULL,
  `content` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/brokerage/BrokerageRecordDO.java
CREATE TABLE IF NOT EXISTS `trade_brokerage_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `biz_id` varchar(255) NULL,
  `biz_type` int NULL,
  `title` varchar(255) NULL,
  `description` varchar(255) NULL,
  `price` int NULL,
  `total_price` int NULL,
  `status` int NULL,
  `frozen_days` int NULL,
  `unfreeze_time` datetime NULL,
  `source_user_level` int NULL,
  `source_user_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/brokerage/BrokerageUserDO.java
CREATE TABLE IF NOT EXISTS `trade_brokerage_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `bind_user_id` bigint NULL,
  `bind_user_time` datetime NULL,
  `brokerage_enabled` bit NULL,
  `brokerage_time` datetime NULL,
  `brokerage_price` int NULL,
  `frozen_price` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/brokerage/BrokerageWithdrawDO.java
CREATE TABLE IF NOT EXISTS `trade_brokerage_withdraw` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `price` int NULL,
  `fee_price` int NULL,
  `total_price` int NULL,
  `type` int NULL,
  `user_name` varchar(255) NULL,
  `user_account` varchar(255) NULL,
  `qr_code_url` text NULL,
  `bank_name` varchar(255) NULL,
  `bank_address` varchar(255) NULL,
  `status` int NULL,
  `audit_reason` varchar(255) NULL,
  `audit_time` datetime NULL,
  `remark` varchar(255) NULL,
  `pay_transfer_id` bigint NULL,
  `transfer_channel_code` varchar(255) NULL,
  `transfer_time` datetime NULL,
  `transfer_error_msg` varchar(255) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/cart/CartDO.java
CREATE TABLE IF NOT EXISTS `trade_cart` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `spu_id` bigint NULL,
  `sku_id` bigint NULL,
  `student_id` bigint NULL,
  `count` int NULL,
  `selected` bit(1) NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_sku` (`user_id`, `sku_id`),
  KEY `idx_trade_cart_learner` (`user_id`, `sku_id`, `student_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/config/TradeConfigDO.java
CREATE TABLE IF NOT EXISTS `trade_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `after_sale_refund_reasons` text NULL,
  `after_sale_return_reasons` text NULL,
  `delivery_express_free_enabled` bit(1) NULL,
  `delivery_express_free_price` int NULL,
  `delivery_pick_up_enabled` bit(1) NULL,
  `brokerage_enabled` bit(1) NULL,
  `brokerage_enabled_condition` int NULL,
  `brokerage_bind_mode` int NULL,
  `brokerage_poster_urls` text NULL,
  `brokerage_first_percent` int NULL,
  `brokerage_second_percent` int NULL,
  `brokerage_withdraw_min_price` int NULL,
  `brokerage_withdraw_fee_percent` int NULL,
  `brokerage_frozen_days` int NULL,
  `brokerage_withdraw_types` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NULL,
  `name` varchar(255) NULL,
  `logo` varchar(255) NULL,
  `sort` int NULL,
  `status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressTemplateDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `charge_mode` int NULL,
  `sort` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressTemplateChargeDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express_template_charge` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NULL,
  `area_ids` text NULL,
  `charge_mode` int NULL,
  `start_count` double NULL,
  `start_price` int NULL,
  `extra_count` double NULL,
  `extra_price` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryExpressTemplateFreeDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_express_template_free` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NULL,
  `area_ids` text NULL,
  `free_price` int NULL,
  `free_count` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/delivery/DeliveryPickUpStoreDO.java
CREATE TABLE IF NOT EXISTS `trade_delivery_pick_up_store` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NULL,
  `introduction` varchar(255) NULL,
  `phone` varchar(255) NULL,
  `area_id` int NULL,
  `detail_address` text NULL,
  `logo` varchar(255) NULL,
  `opening_time` time NULL,
  `closing_time` time NULL,
  `latitude` double NULL,
  `longitude` double NULL,
  `verify_user_ids` text NULL,
  `status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/order/TradeOrderDO.java
CREATE TABLE IF NOT EXISTS `trade_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(255) NULL,
  `type` int NULL,
  `terminal` int NULL,
  `user_id` bigint NULL,
  `user_ip` varchar(255) NULL,
  `user_remark` varchar(255) NULL,
  `status` int NULL,
  `product_count` int NULL,
  `finish_time` datetime NULL,
  `cancel_time` datetime NULL,
  `cancel_type` int NULL,
  `remark` varchar(255) NULL,
  `comment_status` boolean NULL,
  `brokerage_user_id` bigint NULL,
  `pay_order_id` bigint NULL,
  `pay_status` bit NULL,
  `pay_time` datetime NULL,
  `pay_channel_code` varchar(255) NULL,
  `total_price` int NULL,
  `discount_price` int NULL,
  `delivery_price` int NULL,
  `adjust_price` int NULL,
  `pay_price` int NULL,
  `delivery_type` int NULL,
  `logistics_id` bigint NULL,
  `logistics_no` varchar(255) NULL,
  `delivery_time` datetime NULL,
  `receive_time` datetime NULL,
  `receiver_name` varchar(255) NULL,
  `receiver_mobile` varchar(255) NULL,
  `receiver_area_id` int NULL,
  `receiver_detail_address` varchar(255) NULL,
  `pick_up_store_id` bigint NULL,
  `pick_up_verify_code` varchar(255) NULL,
  `refund_status` int NULL,
  `refund_price` int NULL,
  `coupon_id` bigint NULL,
  `coupon_price` int NULL,
  `use_point` int NULL,
  `point_price` int NULL,
  `give_point` int NULL,
  `refund_point` int NOT NULL DEFAULT 0,
  `vip_price` int NULL,
  `give_coupon_template_counts` text NULL,
  `give_coupon_ids` text NULL,
  `seckill_activity_id` bigint NULL,
  `bargain_activity_id` bigint NULL,
  `bargain_record_id` bigint NULL,
  `combination_activity_id` bigint NULL,
  `combination_head_id` bigint NULL,
  `combination_record_id` bigint NULL,
  `point_activity_id` bigint NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/order/TradeOrderItemDO.java
CREATE TABLE IF NOT EXISTS `trade_order_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `order_id` bigint NULL,
  `cart_id` int NULL,
  `spu_id` bigint NULL,
  `spu_name` varchar(255) NULL,
  `sku_id` bigint NULL,
  `student_id` bigint NULL,
  `properties` text NULL,
  `pic_url` varchar(255) NULL,
  `count` int NULL,
  `comment_status` boolean NULL,
  `price` int NULL,
  `discount_price` int NULL,
  `delivery_price` int NULL,
  `adjust_price` int NULL,
  `pay_price` int NULL,
  `coupon_price` int NULL,
  `point_price` int NULL,
  `use_point` int NULL,
  `give_point` int NULL,
  `vip_price` int NULL,
  `after_sale_id` bigint NULL,
  `after_sale_status` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_spu_id` (`spu_id`),
  KEY `idx_sku_id` (`sku_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_trade_order_item_learner` (`student_id`, `sku_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-trade/src/main/java/cn/iocoder/yudao/module/trade/dal/dataobject/order/TradeOrderLogDO.java
CREATE TABLE IF NOT EXISTS `trade_order_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NULL,
  `user_type` int NULL,
  `order_id` bigint NULL,
  `before_status` int NULL,
  `after_status` int NULL,
  `operate_type` int NULL,
  `content` text NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apps/server/yudao-module-mall/yudao-module-statistics/src/main/java/cn/iocoder/yudao/module/statistics/dal/dataobject/trade/TradeStatisticsDO.java
CREATE TABLE IF NOT EXISTS `trade_statistics` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `time` datetime NULL,
  `order_create_count` int NULL,
  `order_pay_count` int NULL,
  `order_pay_price` int NULL,
  `after_sale_count` int NULL,
  `after_sale_refund_price` int NULL,
  `brokerage_settlement_price` int NULL,
  `wallet_pay_price` int NULL,
  `recharge_pay_count` int NULL,
  `recharge_pay_price` int NULL,
  `recharge_refund_count` int NULL,
  `recharge_refund_price` int NULL,
  `creator` varchar(255) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

