import React,{useRef,useState} from 'react';
import {Modal} from './components';
import {educationRequest} from './education-api';
export default function InquiryForm({onClose}){
 const [values,setValues]=useState({name:'',contact:'',experience:'刚刚开始',interest:'还在探索',message:'',consent:false});
 const [saving,setSaving]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 const requestId=useRef(crypto.randomUUID());
 const change=e=>{setValues(v=>({...v,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));setError('')};
 async function submit(e){e.preventDefault();if(saving)return;setSaving(true);setError('');try{const result=await educationRequest('/inquiries',{method:'POST',body:JSON.stringify({...values,name:values.name.trim(),contact:values.contact.trim(),requestId:requestId.current})});setReceipt(result.receipt)}catch(err){setError(err.name==='TimeoutError'?'请求超时，可以重试；系统会避免重复记录。':err.message)}finally{setSaving(false)}}
 return <Modal title={receipt?'咨询已收到':'聊聊孩子的学习兴趣'} onClose={onClose} className="reservation-modal">{receipt?<div role="status"><h3>已提交至课程咨询后台</h3><p>我们将根据你留下的联系方式进一步沟通。</p><p>请勿重复提交；课程安排以沟通确认的信息为准。</p><button className="button button-primary" onClick={onClose}>完成</button></div>:<form onSubmit={submit}><p className="modal-intro">留下联系方式与感兴趣的方向，方便进一步了解课程。</p><div className="form-grid"><label>家长称呼<input required name="name" autoComplete="name" value={values.name} onChange={change} maxLength={40}/></label><label>手机号或邮箱<input required name="contact" value={values.contact} onChange={change} maxLength={120} autoComplete="email" pattern="(1[3-9][0-9]{9}|[^\s@]+@[^\s@]+\.[^\s@]+)" title="请填写有效的手机号或邮箱"/></label><label>已有经验<select name="experience" value={values.experience} onChange={change}>{['刚刚开始','尝试过图形化编程','写过一些代码','接触过 AI 创作'].map(s=><option key={s}>{s}</option>)}</select></label><label>感兴趣的方向<select name="interest" value={values.interest} onChange={change}>{['还在探索','创意启蒙','AI 项目创作','作品成长计划'].map(s=><option key={s}>{s}</option>)}</select></label></div><label style={{display:'grid',gap:8,marginTop:16}}>想了解什么（选填）<textarea name="message" value={values.message} onChange={change} maxLength={1000} rows={3}/></label><label style={{display:'flex',alignItems:'flex-start',gap:10,fontSize:13,margin:'20px 0'}}><input type="checkbox" required name="consent" checked={values.consent} onChange={change} style={{width:18,marginTop:3}}/>同意将以上信息用于本次课程咨询与联系。无需提供孩子姓名或身份资料。</label>{error&&<p role="alert" className="field-error">{error}</p>}<button type="submit" disabled={saving} className="button button-primary full-width">{saving?'正在提交…':'提交课程咨询'}</button></form>}</Modal>;
}
