-- Generated education differences only; accounts/trade/pay/files stay in original upstream tables.

-- Generated by scripts/generate-edu-models.mjs. MySQL8.4 InnoDB.

CREATE TABLE IF NOT EXISTS edu_student (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guardian_member_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  birth_month varchar(255) NOT NULL,
  grade varchar(255) NULL,
  experience longtext NULL,
  version int NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_guardian (tenant_id,guardian_member_id,deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_course (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  spu_id bigint NULL,
  name varchar(255) NOT NULL,
  code varchar(255) NOT NULL,
  description longtext NULL,
  cover_url longtext NULL,
  age_min int NULL,
  age_max int NULL,
  direction varchar(255) NULL,
  level varchar(255) NULL,
  status varchar(255) NOT NULL,
  version int NULL,
  revision int NULL,
  objectives longtext NULL,
  outcomes longtext NULL,
  lessons_json longtext NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_code (tenant_id,code),
  UNIQUE KEY uk_spu (tenant_id,spu_id),
  CHECK(age_min >= 0 AND age_max >= age_min),
  KEY ix_public (tenant_id,status,direction)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_course_version (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  course_id bigint NOT NULL,
  version int NOT NULL,
  name varchar(255) NOT NULL,
  content_json longtext NOT NULL,
  published_at datetime(3) NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_version (tenant_id,course_id,version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_lesson_template (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  course_version_id bigint NOT NULL,
  title varchar(255) NOT NULL,
  sort int NOT NULL,
  duration_minutes int NULL,
  objectives longtext NULL,
  materials longtext NULL,
  assignment longtext NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_lesson (tenant_id,course_version_id,sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_campus (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  city varchar(255) NULL,
  address longtext NULL,
  latitude varchar(255) NULL,
  longitude varchar(255) NULL,
  description longtext NULL,
  status varchar(255) NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_dept (tenant_id,dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_room (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  campus_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  capacity int NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_campus (tenant_id,campus_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_teacher_profile (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  bio longtext NULL,
  avatar_url longtext NULL,
  status varchar(255) NOT NULL,
  one_to_one_enabled bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_teacher (tenant_id,user_id),
  KEY ix_one_to_one_public (tenant_id,status,one_to_one_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_cohort (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  course_id bigint NOT NULL,
  course_version_id bigint NULL,
  sku_id bigint NULL,
  name varchar(255) NOT NULL,
  kind varchar(255) NOT NULL,
  mode varchar(255) NOT NULL,
  campus_id bigint NULL,
  room_id bigint NULL,
  teacher_id bigint NULL,
  capacity int NOT NULL,
  status varchar(255) NOT NULL,
  start_date datetime(3) NULL,
  end_date datetime(3) NULL,
  terms longtext NULL,
  refund_policy longtext NULL,
  version int NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_sku (tenant_id,sku_id),
  KEY ix_course (tenant_id,course_id,status),
  KEY ix_campus (tenant_id,campus_id,status),
  CHECK(capacity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_session (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cohort_id bigint NOT NULL,
  lesson_template_id bigint NULL,
  title varchar(255) NOT NULL,
  start_time datetime(3) NOT NULL,
  end_time datetime(3) NOT NULL,
  teacher_id bigint NOT NULL,
  room_id bigint NULL,
  join_info longtext NULL,
  materials_json longtext NULL,
  status varchar(255) NOT NULL,
  version int NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_cohort_time (tenant_id,cohort_id,start_time),
  KEY ix_teacher_time (tenant_id,teacher_id,start_time,end_time),
  KEY ix_room_time (tenant_id,room_id,start_time,end_time),
  CHECK(end_time > start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_session_teacher (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  session_id bigint NOT NULL,
  user_id bigint NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_session_teacher (tenant_id,session_id,user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_order_item_ext (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_item_id bigint NOT NULL,
  student_id bigint NOT NULL,
  purchased_cohort_id bigint NOT NULL,
  snapshot_json longtext NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_order_item (tenant_id,order_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_enrollment (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id bigint NOT NULL,
  current_cohort_id bigint NOT NULL,
  order_item_id bigint NULL,
  trial_booking_id bigint NULL,
  source varchar(255) NOT NULL,
  status varchar(255) NOT NULL,
  version int NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  active_key tinyint GENERATED ALWAYS AS (CASE WHEN deleted=0 AND status IN ('PENDING_PAYMENT','ACTIVE','COMPLETED') THEN 1 ELSE NULL END) STORED,
  UNIQUE KEY uk_active_student (tenant_id,student_id,current_cohort_id,active_key),
  UNIQUE KEY uk_order_item (tenant_id,order_item_id),
  UNIQUE KEY uk_trial (tenant_id,trial_booking_id),
  CHECK((source='ORDER' AND order_item_id IS NOT NULL AND trial_booking_id IS NULL) OR (source='FREE_TRIAL' AND trial_booking_id IS NOT NULL AND order_item_id IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_trial_booking (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id bigint NOT NULL,
  cohort_id bigint NOT NULL,
  status varchar(255) NOT NULL,
  order_item_id bigint NULL,
  crm_clue_id bigint NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_student (tenant_id,student_id,status),
  KEY ix_crm_clue (tenant_id,crm_clue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_seat_hold (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_item_id bigint NOT NULL,
  enrollment_id bigint NOT NULL,
  cohort_id bigint NOT NULL,
  expires_at datetime(3) NOT NULL,
  status varchar(255) NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_order_item (tenant_id,order_item_id),
  KEY ix_expiry (tenant_id,status,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_leave_request (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id bigint NOT NULL,
  enrollment_id bigint NOT NULL,
  session_id bigint NOT NULL,
  reason longtext NOT NULL,
  status varchar(255) NOT NULL,
  decision_reason longtext NULL,
  decided_by bigint NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_enrollment (tenant_id,enrollment_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_transfer_request (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id bigint NOT NULL,
  enrollment_id bigint NOT NULL,
  from_cohort_id bigint NOT NULL,
  target_cohort_id bigint NOT NULL,
  reason longtext NOT NULL,
  status varchar(255) NOT NULL,
  decision_reason longtext NULL,
  decided_by bigint NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_enrollment (tenant_id,enrollment_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_transfer_event (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  enrollment_id bigint NOT NULL,
  from_cohort_id bigint NOT NULL,
  target_cohort_id bigint NOT NULL,
  request_id bigint NOT NULL,
  actor_id bigint NOT NULL,
  reason longtext NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_request (tenant_id,request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_attendance (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  enrollment_id bigint NOT NULL,
  session_id bigint NOT NULL,
  status varchar(255) NOT NULL,
  note longtext NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_attendance (tenant_id,enrollment_id,session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_assignment (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cohort_id bigint NOT NULL,
  session_id bigint NULL,
  title varchar(255) NOT NULL,
  description longtext NULL,
  due_time datetime(3) NULL,
  materials_json longtext NULL,
  status varchar(255) NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  KEY ix_cohort_due (tenant_id,cohort_id,due_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_submission (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  assignment_id bigint NOT NULL,
  student_id bigint NOT NULL,
  enrollment_id bigint NOT NULL,
  version int NOT NULL,
  content longtext NULL,
  attachments_json longtext NULL,
  status varchar(255) NOT NULL,
  submitted_at datetime(3) NULL,
  revision int NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_submission (tenant_id,assignment_id,enrollment_id,version),
  KEY ix_workqueue (tenant_id,status,submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_review (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  submission_id bigint NOT NULL,
  teacher_id bigint NOT NULL,
  feedback longtext NULL,
  score int NULL,
  status varchar(255) NOT NULL,
  require_revision bit(1) NULL,
  published_at datetime(3) NULL,
  revision int NOT NULL DEFAULT 0,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_submission_review (tenant_id,submission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_growth_report (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id bigint NOT NULL,
  enrollment_id bigint NOT NULL,
  title varchar(255) NOT NULL,
  content longtext NULL,
  dimensions_json longtext NULL,
  status varchar(255) NOT NULL,
  version int NULL,
  published_at datetime(3) NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_after_sale_ext (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  after_sale_id bigint NOT NULL,
  enrollment_id bigint NOT NULL,
  entitlement_action varchar(255) NOT NULL,
  enrollment_version int NOT NULL,
  stock_released bit(1) NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_aftersale (tenant_id,after_sale_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_work (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id bigint NOT NULL,
  submission_id bigint NOT NULL,
  title varchar(255) NOT NULL,
  description longtext NULL,
  version int NOT NULL,
  status varchar(255) NOT NULL,
  cover_url longtext NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_work_version (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  work_id bigint NOT NULL,
  version int NOT NULL,
  submission_id bigint NOT NULL,
  content_json longtext NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_version (tenant_id,work_id,version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_publish_consent (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  work_id bigint NOT NULL,
  version int NOT NULL,
  guardian_member_id bigint NOT NULL,
  status varchar(255) NOT NULL,
  granted_at datetime(3) NULL,
  revoked_at datetime(3) NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_consent (tenant_id,work_id,version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_publication (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  work_id bigint NOT NULL,
  version int NOT NULL,
  status varchar(255) NOT NULL,
  moderator_id bigint NULL,
  moderation_note longtext NULL,
  published_at datetime(3) NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_publication (tenant_id,work_id,version),
  KEY ix_public (tenant_id,status,published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS edu_file_access (
  id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  file_id bigint NOT NULL,
  student_id bigint NULL,
  cohort_id bigint NULL,
  owner_member_id bigint NULL,
  name varchar(255) NOT NULL,
  purpose varchar(255) NOT NULL,
  sha256 varchar(255) NULL,
  status varchar(255) NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  creator varchar(64) NULL DEFAULT '',
  updater varchar(64) NULL DEFAULT '',
  create_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted bit(1) NOT NULL DEFAULT b'0',
  UNIQUE KEY uk_file (tenant_id,file_id),
  KEY ix_owner (tenant_id,owner_member_id,student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
